### PR TITLE
README: Update Common Form link

### PR DESCRIPTION
**Pull request by jeremy-w**
The prior URL is 404ing as of now.

### CODE REVIEW

**Comment by kemitchell** [comment]
Right you are! Thanks for this!

**Comment by jeremy-w** [comment]
Oops, I think it probably shoulda gone to: https://commonform.org/switchmode where switchmode itself is a publisher.

**Comment by jeremy-w** [comment]
You beat me to merge while I was adding a follow-up commit on this branch. :)

**Comment by kemitchell** [comment]
I'll rewind.

**Comment by kemitchell** [comment]
All taken care of.

**Pull request merged**
